[package]
name = "obsidian-config-manager"
version = "0.1.0"
edition = "2021"
authors = ["Juan Manuel Young Hoyos <juanmanuel12.13jmyh81@gmail.com>"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
